### ISSUE TITLE
Links relative to env

### ISSUE THREAD

**Issue by varatep** [open-horizon/anax-ui#1]
Links should be relative to environment (staging.bluehorizon.hovitos.engineering vs bluehorizon.network)

**Comment by bmpotter** [comment]
Varatep,

I thought this was fixed, but was mistaken. Still can't use the reg UI for staging, which means the reg UI doesn't get tested enough.

**Comment by varatep** [comment]
@bmpotter This should have been fixed back when @michaeldye fixed the ANAX API `/status` call. Can you please confirm this?

**Comment by varatep** [comment]
@bmpotter Looks like the fixed API only updates the *exchange url* and not the actual links to docs relative to the env. Should the `sensor_url` property in the service attribute mapping also change relative to environment?

**Comment by bmpotter** [comment]
@varatep No, the URLs that point to the identify microservices and workloads and point to the documentation of them, aren't really designed to vary between staging and prod. So don't worry about those. That won't affect the functionality of whether the reg ui can be successfully used to register a device that is pointing to stg.
