### ISSUE TITLE
various improvement requests

### ISSUE THREAD

**Issue by datajerk** [open-horizon/anax-ui#12]
![image](https://cloud.githubusercontent.com/assets/4184031/22444846/edfd157e-e701-11e6-8901-edec362c73ab.png)

You should be able to tell if you are behind a firewall or not and make this more intelligent or stronger warning, the first statement creates unnecessary fear, e.g. if eth0 and `curl ifconfig.co` are a match then clearly change the password.

Or, why not change device password from the webui like any other end user device?

When i mouse over "executing" or other tag, it turns to finger pointer, but if i click nothing, what is the purpose of that?

Please add link or embedded map to show the bluehorizon.network/map at the location of my stuff in the dashboard screen.  Clearly for bluehorizon anax-ui only.

**Comment by bmpotter** [comment]
Consolidated into https://github.com/open-horizon/anax-ui/issues/41
