### ISSUE TITLE
Provide button/field to change the rpi pw, instead of instructions on how to do it

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax-ui#20]

**Comment by varatep** [comment]
Is there/will there be an ANAX API endpoint on the device to allow for this?

**Comment by bmpotter** [comment]
Good point. There isn't an anax api for this yet, but there should be. Discuss w/mike when he's back.

**Comment by bmpotter** [comment]
Consolidated into https://github.com/open-horizon/anax-ui/issues/41
