### ISSUE TITLE
Quick improvements to 1st registration UI page

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax-ui#31]
Until mike can get to implementing the restructuring of the account creation and device registration UX (anax issue 77), we need some short term fixes to improve the experience of new users coming on board now. The changes listed below will stick with the current single page for account creation and device registration, so it doesn't cause too many backend changes or cause redundant work with issue 77.

- add a toggle button indicating whether they already have a user account or not
- when the have an existing account, hide the email field
- fix anax-ui issue 28 at the same time
- modify some of the text on the page to clarify what they should do
- instead of warning them in text that the device can't be owned by another user, handle that case by looking at the http return code you get from exchange when trying to do the `put /devices/{id}`: it will be 403 (access denied) in this case.

**Comment by varatep** [comment]
Hi @bmpotter, is all that's left the last bullet point - 403 error handling?

**Comment by bmpotter** [comment]
Yes, that's everything. Thx for moving on this so quickly!
