### ISSUE TITLE
Password field prefilled with wrong value

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax-ui#39]
On the first page of the UI registration, I allowed the browser to save the password. Next time when this page was brought up,  the password field  showed "........" which had the same length as the password I used before. However, clicking "Associate the Device with the Account" button the following error appeared: 
````
Account Data Error
Account data submission error. Error associating device in Exchange with account "test". Please try again.
````
So please either put correct pre-filled value for the password or make it empty.  It is misleading now.

**Comment by varatep** [comment]
@linggao Is this a result of the pre-filled password from your browser?

**Comment by linggao** [comment]
Yes, I was using Google Chrome.

**Comment by varatep** [comment]
@linggao You'll have to check your saved passwords in Google Chrome for this. This is unrelated to the actual web app itself as the UI does not check or auto-fill any passwords.

**Comment by linggao** [comment]
@varatep the pre-filled password never worked on the reg page no matter how.  I always have to retype the password.

**Comment by varatep** [comment]
@linggao What is the behavior currently? Is the password that is currently being autofilled your actual password or is it another piece of form data?

**Comment by linggao** [comment]
@varatep I cannot determine the data from the prefilled password because it displayed as ".........".  The behavior is that the password field is pre-filled, but cannot be used.

**Comment by varatep** [comment]
@linggao as mentioned above, you can check this in your chrome browser's password management settings. This is in the settings screen of chrome and click on advanced settings to see the manage saved passwords

Varatep Buranintu

**Comment by linggao** [comment]
@varatep  I just checked the setting. The saved the password is correct.

**Comment by linggao** [comment]
Same behavior on FireFox.

**Comment by linggao** [comment]
I put debug info in the code and found out that the password passed in was empty though is showed "...........".  When double clicking the field, it showed "Use password for <my user name>", choosing it resulted in the correct password.  Something is not right for this password field at initialization.

**Comment by linggao** [comment]
When the first page shown, there is a warning in the console which I am not sure if this is related.
````
This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
````
Further debugging found there is a ACCOUNT_FORM_UPDATE action which clears the password field between the first page and the second page of registration.
````
core.js:104  action ACCOUNT_SET @ 16:44:17.428
core.js:116  prev state ...
core.js:120  action     Object {type: "ACCOUNT_SET", accountForm: Object, deviceId: "0000000021700c289"}
core.js:128  next state ...
core.js:104  action ACCOUNT_FORM_UPDATE @ 16:44:17.442
action ACCOUNT_FORM_UPDATE @ 16:44:17.442
core.js:116  prev state ....
core.js:120  action     Object {type: "ACCOUNT_FORM_UPDATE", segment: "account", fieldName: "password", value: ""}
core.js:128  next state ....
````

**Comment by linggao** [comment]
Here is the line that clears the password field after the data submission.   https://github.com/open-horizon/anax-ui/blob/master/src/components/AccountForm/presenter.js#L93
It is useful when the user chooses not to save the password, but causes confusion if the user chooses to save the password.

**Comment by linggao** [comment]
This is a useful article. https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
However, I tried commenting out  https://github.com/open-horizon/anax-ui/blob/master/src/components/AccountForm/presenter.js#L93 and added autocomplete="off" or autocomplete="new-password" to the password field, none of them worked.

So for now, we will not change anything in code until we get a better solution.

**Comment by bmpotter** [comment]
Varatep,

Based on ling's research above, it looks like this is not specific to ling's environment, but instead one of those browser/UI interaction problems that the registration UI code should try to work around. So i'm assigning it back to you.

**Comment by linggao** [comment]
Built in snap revision 124 (arm) and 125 (x86), version 2.0.16.

**Comment by linggao** [comment]
The fix was in https://github.com/open-horizon/anax-ui/pull/58 which removed the getting the saved password.
