### ISSUE TITLE
Illegal character in input

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax-ui#40]
Registration first page, the Username field is pre-filled with username. Clear this field resulted in the  following misleading error. 
````
Account Data Error
Illegal character in input.
````

**Comment by bmpotter** [comment]
Ya, this is pretty ugly. If i start typing 1 or 2 chars in the username field and they were typos so i backspace to the beginning, this big read error msg shows up. I imagine there is a single validation routine and error msg, but for a blank field, it should really just say "Username is required".

**Comment by linggao** [comment]
Built in snap 116 (arm) and 117 (x86), version 2.0.14.

**Comment by bmpotter** [comment]
Ling tested and it is fixed
