### ISSUE TITLE
Anax UI: 1 Citygram Environment Variable Incorrect

### ISSUE THREAD

**Issue by chrod** [open-horizon/anax-ui#46]
Citygram workloads require 4 environment variables to run. Anax UI is only delivering 3 correctly right now (1 is incorrect) causing the workload docker containers to continually restart.

Required:
CG_EMAIL
CG_PASS
CG_RSDDESC
CG_RSDNAME <--- currently shows up as "CG_NAME" when using Anax UI to register.

All that is required for now is to modify the CG_NAME env var to CG_RSDNAME and update Anax UI.

**Comment by linggao** [comment]
Built in snap 116 (arm) and 117 (x86), version 2.0.14.

**Comment by linggao** [comment]
So from the reading of this issue and PR 49, the correct setting should be the following for now. And I tested the snap 117, it shows the correct env variables.
HZN_CG_EMAIL
HZN_CG_PASS
HZN_CG_RSDDESC
HZN_CG_RSDNAME
