### ISSUE TITLE
Update registration UI for MS/workload split

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax-ui#54]
See https://docs.google.com/document/d/1jr8X0x6k_ahRvt4gOWQss73ba26-npkl3aGlQj87T7A/edit#heading=h.v2jqo9w1iqqb for a description of the new registration UX, altho this is outdated now. The complete UX described in the design above can be streamlined a little for now to save time:

- For pattern registration:
    - give them a list of patterns to select 1
    - when they select a pattern, show the description, MSs, and workloads
    - prompt the user for the userInput variables and then register the node
- For MS registration:
    - Query the microservice definitions from the exchang for this architecture and present the list to the user to select 1 or more.
    - When he selects an MS, show the workloads in the right-hand column that use that MS
    - (After anax issue #291 is complete, optionally let them select 1 or more workloads as the exact workloads that should be run on this node.)
    - prompt the user for the userInput variables and then register the node

These items need to be completed or fixed in the current registration UI:

- [x] check for/handle errors from all anax and exchange API calls and report errors that can't be handled to user
- [x] update 1st page according to ling's chart and my comments
- [x] use new workload info in agreement api as title for agreement in dashboard
- [x] on dashboard agreements, always show fields like finalized and data received, even when they are still blank, so the page doesn't reformat, and so they know what they are waiting for (eventually data received should only be shown if the agreement has data verification enabled)
- [ ] why is the "Select a pattern" label itself a drop-down?
- [ ] implement MS registration as described above

**Comment by varatep** [comment]
@bmpotter Will the ANAX API change in any way to accommodate the ms/workload split? Will it be the same endpoint?

**Comment by varatep** [comment]
Current status:

Pattern
=
- [x] User input fields for workloads
- [ ] User input fields for microservices

Citizen Scientist / MSWL Split
=
- [x] Microservice-first approach (user selects microservices they want to use and workloads become available based on that)
- [ ] User input fields for workloads
- [ ] User input fields for microservices
- [ ] Show required microservices in the workload "cards"
