### ISSUE TITLE
"Invalid date" on dashboard 

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax-ui#6]
On the dashboard it showed "Agreement data received by counterparty at: Invalid date". 
The dashboard show this:
Counterparty: agbot-lon02-01.bluehorizon.hovitos.engineering
Counterparty accepted at: January 20, 11:17 AM
Workload pattern deployed at: January 20, 11:17 AM
Agreement data received by counterparty at: Invalid date
Agreement finalized at: January 20, 11:18 AM

The api shows this:
{
  "name": "Policy for netspeed merged with netspeed amd64",
  "current_agreement_id": "387edcdf76426e267d856dfba3e4fea80c91081b26b8282d1558c8db035370bf",
  "consumer_id": "agbot-lon02-01.bluehorizon.hovitos.engineering",
  "agreement_creation_time": 1484928959,
  "agreement_accepted_time": 1484929026,
  "agreement_finalized_time": 1484929046,
  "agreement_data_received_time": 1484929072,
  "agreement_execution_start_time": 1484929033
}
{
  "name": "Policy for location merged with location amd64",
  "current_agreement_id": "447da405e043bd16aee6e0b71798f6bf707a077d19a4ef5ea7f1b47b5073760b",
  "consumer_id": "agbot-lon02-01.bluehorizon.hovitos.engineering",
  "agreement_creation_time": 1484929004,
  "agreement_accepted_time": 1484929027,
  "agreement_finalized_time": 1484929107,
  "agreement_data_received_time": 1484929073,
  "agreement_execution_start_time": 1484929038
}

**Comment by michaeldye** [comment]
Fix merged in ff30f04eb3b88d9e95310df23b2cd0b6eeabdb4a
