### ISSUE TITLE
Wrong link for SDR

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax-ui#69]
On the "Service Selection" page, the link "Hardware required: USB RTL-SDR Kit: Dongle and antenna" under SDR is currently pointing to "https://bluehorizon.network/documentation/rpi2" which is blank for bluehorizon web.

**Comment by varatep** [comment]
PR #80 has a fix for this issue by pointing to the new location https://bluehorizon.network/documentation/rpi-hardware
