### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested 

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax-ui#70]
Reflashed the rpi with latest snap (revision 126), pointed the rpi against staging. 
On the first page of registration UI, turn on "I have an account with Horizon", entered correct credentials then clicked "Associate this device with account" button.  An error box appears it says 
```
Account Data Error
Account data submission error. undefined
```
The browser console showed the following error.
```
Fetch API cannot load https://exchange.staging.bluehorizon.network/api/v1/devices. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.182' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
accountForm.js:224 Error occurred registering account, device, etc. TypeError: Failed to fetch
```

**Comment by linggao** [comment]
Googling found the following helpful information:
Looks like your server does not include the Access-Control-Allow-Origin header in response to a preflight request (OPTIONS). A CORS request will fail if Access-Control-Allow-Origin is missing.
Here are some great articles that explain how CORS works:
https://www.html5rocks.com/en/tutorials/cors/
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by linggao** [comment]
Tried the same snap against production, the registration first page worked.

**Comment by bmpotter** [comment]
Had to disable the builtin CorsSupport and explicitly set the Access-Control-* values so Access-Control-Allow-Origin would get set. Pushed to staging.

**Comment by bmpotter** [comment]
Varatep tested on prod and confirmed it was fixed.
