### ISSUE TITLE
Improvements for Terminated Agreements

### ISSUE THREAD

**Issue by varatep** [open-horizon/anax-ui#74]
Continued from https://github.com/open-horizon/anax-ui/issues/61#issuecomment-315050614

- [ ] Detailed page for agreement segment in Terminated Agreements list
- [ ] Dynamic property rendering for agreement (Need a list of items that we want to show on the short widget so I can filter those out to be rendered)

This issue is to keep track of the improvements to be made on the `Terminated Agreements` segment of the dashboard.

**Comment by bmpotter** [comment]
What are the specific follow-on items you are tracking for this issue?

**Comment by varatep** [comment]
@bmpotter This is for @dabooz's comment that is linked. I've updated the OP with two items to start off. These items are to be discussed further and confirmed before starting work on it.
