### ISSUE TITLE
pattern page hung

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax-ui#96]
Testing against staging with horizon 2.13.1 from my rpi3. When I used the default organization "public" on the first setup page, then proceeded to the third page which is supposed to display the pattern selection box. The page hung with "Loading" displayed. However, if I chose "IBM" on the first page, the third page displayed correct information.

**Comment by linggao** [comment]
There are no patterns defined for "public" organization at the time of testing.

**Comment by varatep** [comment]
@linggao This issue is pretty old. Has it been resolved? Can you close if so?
